[build]
  publish = "/public"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/hello-template"
  function = "transform-hello-template"

[[edge_functions]]
  path = "/robloxWebhook"
  function = "robloxWebhook"




