[build]
  publish = "/public"
  functions = "netlify/functions"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/hello-template"
  function = "transform-hello-template"

[[edge_functions]]
  path = "/record-command"
  function = "record-command"




